Atualiza precificação internacional para webservice REST
claudiosmweb/woocommerce-correios pull request #167
Opened 2019-10-03 03:40 UTC by gutobenn

Este PR atualiza a precificação de envios internacionais para utilizar o novo componente `Preço e Prazo Internacional REST`, uma vez que, conforme a issue #126, o utilizado até então não está mais disponível.

A documentação do componente está disponível em https://cws2.correios.com.br/static/swagger/?url=/precoprazoservice/rs/swagger.json

Os dados de homologação são usuário `correioslogtest` e senha `123456`, conforme esse [pdf](http://blog.correios.com.br/correioslog/wp-content/uploads/2017/12/Correios-Web-Service-Padr%C3%B5es-T%C3%A9cnicos-de-Comunica%C3%A7%C3%A3o-do-Servi%C3%A7o-e-fulfillment_v2-5.pdf).

Por enquanto apenas os preços são exibidos. Para calcular o prazo é necessário passar o código da cidade (`coCidadeDestino`) na chamada.
Estou com um pouco de dúvida nos serviços adicionais também, pois ainda não tenho certeza de quais são os códigos e quando usá-los.

2019-10-08 14:39 UTC, claudiosanches requested changes
Tem alguns pequenos problemas para corrigir antes, mas já agradeço pela ajuda.
Qual documentação dos Correios você usou?

2019-10-08 14:39 UTC, claudiosanches commented on includes/class-wc-correios-webservice-international.php
> +			'ATF',
Não vi qualquer "ATF" na lista, também o WooCommerce suporta apenas com 2 letras.

2019-10-08 14:39 UTC, claudiosanches commented on includes/class-wc-correios-webservice-international.php
> -	public function get_origin_state() {
Você esta removendo métodos públicos, isso vai gerar problemas de compatibilidade, se alguém esta estendendo essa classe.

2019-10-08 14:39 UTC, claudiosanches commented on includes/class-wc-correios-webservice-international.php
> -	public function get_origin_state() {
Métodos sem uso devem ser mantidos e usar a tag `@deprecated`.

2019-10-08 14:39 UTC, claudiosanches commented on includes/class-wc-correios-webservice-international.php
> +				$this->log->add( $this->id, 'Success: ' . print_r( $result, true ) );
Não use `print_r()` aqui, deve usar `wc_print_r()` no lugar.

2019-10-08 14:39 UTC, claudiosanches commented on includes/abstracts/class-wc-correios-shipping-international.php
> +		/* TODO
Tem informações na API nova sobre o prazo?
Se tiver já seria bom implementar nesta versão, ou remover este código.

2019-11-20 15:36 UTC, diegosomar commented
Olá! O usuário e senha solicitados, referem-se ao contrato com os Correios? Parece que é obrigatório informar um usuário e senha mas não sei a que se refere. Pode ajudar?

2019-11-20 19:01 UTC, gutobenn commented
@diegosomar Tem que logar em https://apps.correios.com.br/idCorreios e depois clicar em "Componentes com permissão de acesso recebida" (https://apps.correios.com.br/idCorreios/idCorreios/gerenciar-componentes/ajuda-gerenciar-componentes.jsf). Nessa página tem um campo para definir a senha de acesso aos componentes.
Talvez tenha que pedir para tua agência habilitar o acesso à API de precificação internacional.

Já alerto que o código atual deste PR tem alguns problemas (ele está usando a unidade de peso errada, por exemplo). Na minha versão customizada do plugin já corrigi isso, mas ainda não tive tempo de aplicar as correções aqui.

2019-11-20 20:09 UTC, diegosomar commented
@gutobenn Obrigado pela resposta. Vou me cadastrar nos Correios.
Mas vou aguardar então um pouco mais para usar a precificação internacional, para quando as modificações estejam implementadas. Acho que é mais seguro. Um abraço!

2019-11-22 22:17 UTC, wagnerjaccoud commented
Infelizmente me parecer que não está está funcionando um link dos correios o qual conseguimos pedir essa permissão de acesso aos componentes. Já entrei em contato com agência afim de resolver isso. Baixei a sua versão do plugin, caso possa compartilhar uma senha e usuário válido para que possamos testar me envie wagner.jaccoud@gmail.com caso consiga um tempo tento ajudar no desenvolvimento.

2020-10-09 03:40 UTC, gutobenn commented
@claudiosanches, fiz as alterações que você sugeriu, assim como outras correções. Também adicionei o cálculo de prazo e novos métodos de envio. 

No cálculo de prazo internacional é necessário incluir na chamada para a API o parâmetro `coCidadeDestino`, que representa o código da cidade de destino. Esse código é próprio dos Correios (não é um padrão internacional, por exemplo). Então a solução mais simples que encontrei foi escolher a primeira cidade do país, usando outra chamada de API, para gerar o trecho de código em que estão hardcoded um código de cidade para cada país. Fiz [este script](https://gist.github.com/gutobenn/825009c9dcd2da77f4f65db0b7965bad) para gerar o array `$country_first_city`, mas não soube o que fazer com ele.
Fiz alguns testes com alguns países, usando diferentes cidades de diferentes regiões, e o prazo retornado foi igual em todos os casos. Então não é garantido, claro, mas aparentemente não é comum haver diferença. Também vale salientar que o código da cidade só é utilizado para o cálculo de prazo, e não de preço - que é fixo por país.

Links úteis:
- [documentação do componente](https://cws2.correios.com.br/static/swagger/?url=/precoprazoservice/rs/swagger.json) 
- [calculadora oficial de preços e prazos internacionais](https://apps2.correios.com.br/efi/app/simulaPrecoPrazoInternacional/index.php)

@claudiosanches caso precise de uma conta dos Correios com acesso ao componente de precificação internacional, me envia um e-mail que te passo.

2020-10-24 17:44 UTC, tavaresdavi677 commented
Como vai a integração? irá fazer a atualização do plugin com a nova feature em breve? Abraços

2020-12-24 17:39 UTC, vaporwavie commented
Tem algum prazo de conclusão para esse merge? É uma entrega e tanto =)

2021-03-15 16:24 UTC, claudiosanches approved these changes
Muito obrigado por toda a sua ajuda.

2021-03-15 16:24 UTC, merged

2021-06-04 14:47 UTC, renatojandere commented
Olá, pessoal.

Estou utilizando esta versão de vocês em minha loja e já possuo uma conta comercial com os Correios, para a qual já defini uma senha de acesso aos componentes; mas, infelizmente, ainda não consigo obter resposta nas requisições de frete para vendas internacionais. Ao olhar o log, vi que estou recebendo esta mensagem:

![image](https://user-images.githubusercontent.com/60662097/120819196-b5d68d00-c529-11eb-8c7c-05cb1bcb52e9.png)

Entrei em contato com o suporte corporativo dos Correios, fui à agência, falei com muitos funcionários; entretanto, ninguém sabe me dizer com precisão como faço pra habilitar o recurso.

Cheguei a abrir um chamado junto ao suporte a partir do site deles, o qual me foi respondido da seguinte maneira:

![image](https://user-images.githubusercontent.com/60662097/120819569-1665ca00-c52a-11eb-9b24-0ba1193bfc36.png)

Logo, pergunto: isso que eles me informaram procede? Alguém entre vocês está conseguindo usar o recurso do plugin junto aos Correios? Caso sim, qual foi o passo a passo realizado junto aos Correios pra habilitar o recurso?

Obrigado,

2021-06-04 16:32 UTC, gutobenn commented
@renatojandere Estou usando há quase 2 anos e também não foi muito simples para habilitar, teve algumas idas e vindas. Dei uma olhada aqui nos e-mails trocados na época e pelo que entendi o gerente da agência teve que solicitar o acesso a um superior, que encaminhou a solicitação para uma terceira pessoa (talvez superior).
Com base no que escreveram, te sugeriria dizer que deseja utilizar o Exporta Fácil e que, para isso, precisa que habilitem o acesso do teu idCorreios aos seguintes serviços: 192 - Precificação Rest; 292 - Internacional; 234 - Localidades - Países e suas cidades.
Espero que ajude! Depois nos conte se deu certo

2021-06-04 20:21 UTC, renatojandere commented
Obrigado pelas dicas, @gutobenn! Tentarei o que você sugeriu e postarei aqui se deu certo ou não.

2021-07-14 12:57 UTC, renatojandere commented
> 
> 
> Obrigado pelas dicas, @gutobenn! Tentarei o que você sugeriu e postarei aqui se deu certo ou não.

Feedback sobre nossa situação com os Correios: cerca de um mês e meio após fazermos a solicitação junto ao gerente de nossa conta comercial, na própria agência, conseguimos a liberação dos webservices de precificação internacional e o plugin agora está funcionando a contento.

No entanto, foi crucial a informação passada pelo @gutobenn a respeito de quais serviços precisavam ser liberados, pois o próprio gerente não sabia exatamente como subir a solicitação sem uma informação precisa das nossas necessidades.

Portanto, para aqueles que estiverem passando pelas mesmas dificuldades, fica o conselho de ter um pouco de paciência; pois a liberação por parte dos Correios tende a demorar um pouco mesmo.

2021-07-14 14:50 UTC, gutobenn commented
@renatojandere Que ótimo saber que deu certo! 🎉

2023-10-17 14:14 UTC, henrydouglasstm commented
Olá Pessoal, você tem algum exemplo de uma loja virtual que utiliza o calculo de frete internacional via correios?

Eu fiz esta solicitação com as orientações de vocês para o gerente do meu contrato. Mas ele teima que não tem este serviço nos correios e pediu o endereço de uma loja com o calculo de frete internacional dos correios funcionando para ele tentar encamkinhar internamente.

Eu solicitei conforme vocês orientaram aqui, mas esta dificil.

Se vocês não quiserem enviar o endereço da loja por aqui, pode ser por MP.

Eu só preciso disso para ver se os correios adotam uma postura mais cooperativa.

Obrigado a todos desde já.

2023-10-19 02:45 UTC, gutobenn commented
@henrydouglasstm Posso te passar em privado. Me envia um e-mail no endereço que está no meu perfil aqui no github, que aí te respondo com o link.

2023-10-19 02:52 UTC, henrydouglasstm commented
Olá amigo. Segue o meu email: henrydouglasluizdasilva@gmail.com

> @henrydouglasstm Posso te passar em privado. Me envia um e-mail no endereço que está no meu perfil aqui no github, que aí te respondo com o link.

2023-10-19 10:33 UTC, henrydouglasstm commented
Olá, Augusto. Muito obrigado pelo link. Vou encaminhar ao gerente do meu contrato.

2023-11-14 20:13 UTC, henrydouglasstm commented
Olá Prezados, tudo bem?

Primeiramente, quero agradescer a comunidade. A minha plataforma EAD, esta realizando o calculo de frete internacional normalmente agora.

Eu tenho apenas uma duvida:

A o plugin gera o Código de pré postagem internacional depois que o cliente faz a compra no Woococommerce?

Obrigado a todos.

2023-11-14 22:51 UTC, claudiosanches commented
@henrydouglasstm ainda não gera etiqueta de entrega. Ainda precisa fazer isso nos Correios. Mas pretendo integrar isso no plugin um dia.

2023-11-15 11:57 UTC, henrydouglasstm commented
> @henrydouglasstm ainda não gera etiqueta de entrega. Ainda precisa fazer isso nos Correios. Mas pretendo integrar isso no plugin um dia.

Muito obrigado pela resposta.